### PR TITLE
apply sort algorithm on aggregated data

### PR DESCRIPTION
**Pull request by nherment**
Hi @mcollina,

I could not get the tests to pass locally, with my change or without. It's tested in a separate project. I still added the tests but I'm getting The following error:

```
➜  seneca-shard-store git:(master) ✗ npm test

> seneca-shard-store@0.0.6 test /Users/nherment/workspace/seneca-shard-store
> mocha test/


/Users/nherment/workspace/seneca-shard-store/test/shard.test.js:8
var shared = seneca.test.store.shared
                        ^
TypeError: Cannot read property 'store' of undefined
    at Object.<anonymous> (/Users/nherment/workspace/seneca-shard-store/test/shard.test.js:8:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/nherment/workspace/seneca-shard-store/node_modules/mocha/lib/mocha.js:172:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/nherment/workspace/seneca-shard-store/node_modules/mocha/lib/mocha.js:169:14)
    at Mocha.run (/Users/nherment/workspace/seneca-shard-store/node_modules/mocha/lib/mocha.js:356:31)
    at Object.<anonymous> (/Users/nherment/workspace/seneca-shard-store/node_modules/mocha/bin/_mocha:359:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@mcollina @rjrodger @nherment Is this stil relevant? Shall close? The intent is to update this to the new store tests once they are ready.

**Comment by mcollina** [comment]
I have no idea.

**Comment by nherment** [comment]
you'll want to check with Adrian R. It might be relevant for his project. Otherwise it's probably safe to drop.

**Comment by mcdonnelldean** [comment]
@AdrianRossouw what say you? :D

**Comment by AdrianRossouw** [comment]
nope. not used anymore.

**Comment by mcdonnelldean** [comment]
Awesome Cheers all!

**Pull request closed without merging**
